[package]
name = "digital-voting"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.38", features = ["serde"] }
ring = "0.17.8"
serde = { version = "1.0.204", features = ["derive"] }
thiserror = "1.0.63"
bincode = "1.3.3"
anyhow = "1.0.86"
rand = "0.8.5"
actix-web = "4.8.0"
tokio = { version = "1.39.1", features = ["full", "test-util"] }
serde_json = "1.0.120"
base64 = "0.22.1"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
tracing-appender = "0.2.3"
tracing-actix-web = "0.7.11"
# TODO keep in mind that halo2 paralellism may be an issue with Tokio
halo2_proofs = "0.3.0"
halo2_gadgets = "0.3.0"
