[package]
name = "digital-voting"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.38", features = ["serde"] }
ring = "0.17.8"
serde = { version = "1.0.204", features = ["derive"] }
thiserror = "1.0.63"
bincode = "1.3.3"
anyhow = "1.0.86"
rand = "0.8.5"