name: Rust project CI

# TODO probably a good idea to specify specific toolchain versions in the future.

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Build (only check for now)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Prioritizing speed over size here.
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: default
        toolchain: stable
        override: true

    # Not storing the artifacts yet, because the application is too bare bones for now.
    # And since we're not storing artifacts, we can just check instead of build.
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: check
        args: --verbose

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v2

    # Prioritizing speed over size here.
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: default
        toolchain: stable
        override: true

    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --verbose

  formatting:
    name: Check formatting
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v2

    # Prioritizing speed over size here.
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: default
        toolchain: stable
        override: true
  
    - name: Check formatting
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -- --check
  lint:
    name: Run linters
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v2

    # Prioritizing speed over size here.
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: default
        toolchain: stable
        override: true
      
      
    - name: Lint with Clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: -- -D warnings

  dependencies:
    name: Check dependencies
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v2

    # Prioritizing speed over size here.
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: default
        toolchain: stable
        override: true

    - name: Install cargo-deny
      uses: actions-rs/install@v0.1
      with:
        crate: cargo-deny
        version: latest

    - name: Check dependencies with cargo-deny
      run: cargo deny check

    - name: Install cargo-udeps
      uses: actions-rs/install@v0.1
      with:
        crate: cargo-udeps
        version: latest

    - name: Check unused dependencies with cargo-udeps
      run: cargo udeps --all-targets
